### PR TITLE
Added Alert function

### LINKED ISSUE #127: Add flag button

### LINKED ISSUE #128: Connect Flag to backend

### PR DESCRIPTION
**Pull request by Sk3tch7y**
closes #128  and closes #127

### CODE REVIEW

**Comment by Sk3tch7y** [comment]
closes #128 and closes #127

**Review by Nickouwen — APPROVED** [review]
I love cookies and handling them!

**Review by OakleyPankratz — APPROVED** [review]
The code seems well written

**Review by Toughboli — APPROVED** [review]
getCookie is a great helper function. The code is consistent with the rest of the code.

**Pull request merged**
