### PR TITLE
Search bar completed

### PR DESCRIPTION
**Pull request by Sk3tch7y**
Added a search bar and tested input and query logic.

### CODE REVIEW

**Review by Toughboli — APPROVED** [review]
code is clear and readable

**Comment by Nickouwen** [comment]
Class diagram is in the wrong branch. Code looks good

**Review by Nickouwen — COMMENTED** [review]
Class diagram is in the wrong branch. Code looks fine

**Review by OakleyPankratz — COMMENTED** [review]
No issues detected

**Pull request merged**
