### PR TITLE
Alert dashboard

### PR DESCRIPTION
**Pull request by Sk3tch7y**
Created Dashboard element and started logic for querying

### CODE REVIEW

**Review by Sk3tch7y — COMMENTED** [review]
cool stufs

**Review by OakleyPankratz — COMMENTED** [review]
Many small changes and a few additions. No errors or issue in coding practices were detected.

**Comment by Nickouwen** [comment]
We hate DS_Store!
Everything looks good

**Review by Nickouwen — COMMENTED** [review]
Looks good

**Pull request merged**
