### PR TITLE
Querying, search & dashboard stuff working

### LINKED ISSUE #125: Add search bar functionality via API calls

### LINKED ISSUE #135: Populate dashboard with server data

### PR DESCRIPTION
**Pull request by Nickouwen**
Dashboard loads query with searchTerm = "";

Search bar works with partial matching

### CODE REVIEW

**Review by Sk3tch7y — APPROVED** [review]
Looks good, swapping the sample data was smart

**Review by Nickouwen — COMMENTED** [review]
close #125 close #135

**Review by OakleyPankratz — APPROVED** [review]
Code looks good. No issues detected up on review.

**Review by Toughboli — APPROVED** [review]
Code looks consistent, looks like code sells are removed

**Pull request merged**
