### PR TITLE
Added Buttons for adding and removing a post

### LINKED ISSUE #106: Add Bookmark button for data fragments

### LINKED ISSUE #108: Add a remove bookmark button for thumbnails

### PR DESCRIPTION
**Pull request by Sk3tch7y**
tested with console logs closes #108  and closes #106

### CODE REVIEW

**Review by Toughboli — APPROVED** [review]
Looks good. Nothing seems out of order

**Review by Nickouwen — APPROVED** [review]
Buttons worked for me.

**Review by Toughboli — APPROVED** [review]
Code looks clean and functions are focused on single tasks. I like the eyes icon.

**Review by OakleyPankratz — APPROVED** [review]
This is very useful functionality to have implemented. Nice work!

**Pull request merged**
