### PR TITLE
Querying

### LINKED ISSUE #46: Create query functions for government API

### LINKED ISSUE #56: Continue work on Backend Query functionality according to user stories

### PR DESCRIPTION
**Pull request by Nickouwen**
Lots of commits just trying to get Github Actions to work in my fork (nothing to see there),

Moved my exploratory files into server file, changed names to reflect use cases.

Added example of a query and how to import the functions into a new .js file,

Finished querying functionality (it works, but will need to be fine-tuned to provide data Oakley requires),

Began writing tests for query functions (WIP),

Deleted my workflows from this branch in order to not conflict with the main repository's github actions. Will update main repo when I understand it better and more tests are written.

closes #56 
closes #46

### CODE REVIEW

**Comment by Nickouwen** [comment]
Also, I plan on merging testQuerying with Jayden's serverTest.js, which is why my package.json "test" section refers to serverTest and not testQuerying.

**Review by Sk3tch7y — CHANGES_REQUESTED** [review]
I would maybe remove the password from db_connection.js

**Review by Toughboli — APPROVED** [review]
it looks good.

**Review by OakleyPankratz — APPROVED** [review]
Looks good. Querying runs a little slow

**Pull request merged**
