### PR TITLE
mysql database integration

### PR DESCRIPTION
**Pull request by Toughboli**
you can now host a mysql database with docker and use it in the project.

### CODE REVIEW

**Review by Sk3tch7y — COMMENTED** [review]
🤌

**Comment by Nickouwen** [comment]
Looks good

**Review by Nickouwen — COMMENTED** [review]
Looks good

**Review by Sk3tch7y — APPROVED** [review]
cool

**Review by OakleyPankratz — COMMENTED** [review]
No issues detected.

**Pull request merged**
