### PR TITLE
Alerts showing

### PR DESCRIPTION
**Pull request by Sk3tch7y**
Finished alerts search bar functionality

### CODE REVIEW

**Review by Nickouwen — APPROVED** [review]
incredible! Especially love the filterStations function

**Review by Toughboli — APPROVED** [review]
This is a monumental achievement and will innovate the software game for generations! 💯

**Review by Nickouwen — COMMENTED** [review]
Looks great

**Review by OakleyPankratz — APPROVED** [review]
gg gamers. This feature is the icing on the cake for our project. It has been a wonderful semester working with you all.

**Pull request merged**
